const prisma = require('../../config/db');
const TAX_RATE = 0.08;

const normalizeEstimateItems = (items = []) => {
  return (items || []).map(item => {
    const quantity = Number(item.qty ?? item.quantity ?? 0);
    const unitPrice = Number(item.price ?? item.unitPrice ?? 0);
    const safeQty = Number.isFinite(quantity) && quantity > 0 ? quantity : 1;
    const safeUnitPrice = Number.isFinite(unitPrice) && unitPrice > 0 ? unitPrice : 0;
    return {
      description: (item.desc || item.description || 'No description').trim(),
      quantity: safeQty,
      unitPrice: safeUnitPrice,
      total: Number((safeQty * safeUnitPrice).toFixed(2))
    };
  });
};

const calculateTotalsFromItems = (items = []) => {
  const subtotal = Number(items.reduce((sum, item) => sum + Number(item.total || 0), 0).toFixed(2));
  const tax = Number((subtotal * TAX_RATE).toFixed(2));
  const total = Number((subtotal + tax).toFixed(2));
  return { subtotal, tax, total };
};

const normalizeEstimateStatus = (status, fallback = 'PENDING') => {
  if (!status) return fallback;
  const value = String(status).trim().toUpperCase();
  if (value === 'DRAFT' || value === 'PENDING') return 'PENDING';
  if (value === 'APPROVED') return 'APPROVED';
  if (value === 'REVISED') return 'REVISED';
  if (value === 'REJECTED' || value === 'DECLINED') return 'REJECTED';
  return fallback;
};

const getAll = async (user) => {
  const where = user.role === 'CUSTOMER' ? { customerId: user.customer.id } : {};
  return await prisma.estimate.findMany({
    where,
    include: { customer: true, items: true },
    orderBy: { createdAt: 'desc' }
  });
};

const create = async (estimateData) => {
  const { items, projectTitle, notes, customerId, status } = estimateData;
  const mappedItems = normalizeEstimateItems(items);
  const { total } = calculateTotalsFromItems(mappedItems);

  return await prisma.estimate.create({
    data: {
      customerId: parseInt(customerId),
      projectTitle,
      notes,
      status: normalizeEstimateStatus(status),
      totalAmount: total || 0,
      items: {
        create: mappedItems
      }
    },
    include: { items: true, customer: true }
  });
};

const update = async (id, estimateData) => {
  const { items, projectTitle, notes, status } = estimateData;
  const estimateId = parseInt(id);
  const existingEstimate = await prisma.estimate.findUnique({ where: { id: estimateId } });
  const hasItemsUpdate = Array.isArray(items);

  if (hasItemsUpdate) {
    await prisma.estimateItem.deleteMany({ where: { estimateId } });
  }

  const mappedItems = hasItemsUpdate ? normalizeEstimateItems(items) : [];
  const { total } = hasItemsUpdate ? calculateTotalsFromItems(mappedItems) : { total: Number(existingEstimate?.totalAmount || 0) };

  return await prisma.estimate.update({
    where: { id: estimateId },
    data: {
      projectTitle: projectTitle ?? existingEstimate?.projectTitle,
      notes: notes ?? existingEstimate?.notes,
      status: normalizeEstimateStatus(status, existingEstimate?.status || 'PENDING'),
      totalAmount: total,
      ...(hasItemsUpdate ? { items: { create: mappedItems } } : {})
    },
    include: { items: true, customer: true }
  });
};

const approve = async (id) => {
  const estimate = await prisma.estimate.update({
    where: { id: parseInt(id) },
    data: { status: 'APPROVED', approvedAt: new Date(), declinedAt: null },
    include: { customer: true, items: true }
  });

  // Automatically create a job if it doesn't exist
  const existingJob = await prisma.job.findUnique({ where: { estimateId: estimate.id } });
  if (!existingJob) {
    await prisma.job.create({
      data: {
        title: estimate.projectTitle || `${estimate.customer.name}'s Service Job`,
        description: estimate.notes || 'Autogenerated from approved estimate',
        customerId: estimate.customerId,
        estimateId: estimate.id,
        status: 'SCHEDULED'
      }
    });
  }

  return estimate;
};

const remove = async (id) => {
  const estimateId = parseInt(id);
  const jobUsingEstimate = await prisma.job.findUnique({ where: { estimateId } });
  if (jobUsingEstimate) {
    const error = new Error('Cannot delete estimate linked to an existing job');
    error.status = 400;
    throw error;
  }

  await prisma.estimateItem.deleteMany({ where: { estimateId } });
  return await prisma.estimate.delete({ where: { id: estimateId } });
};

module.exports = { getAll, create, update, approve, remove };
