const prisma = require('../../config/db');
const TAX_RATE = 0.08;

const toNumber = (value) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
};

const mapInvoiceWithPricing = (invoice) => {
  const estimateItems = invoice?.job?.estimate?.items || [];
  const subtotal = Number(estimateItems.reduce((sum, item) => sum + toNumber(item.total), 0).toFixed(2));
  const tax = Number((subtotal * TAX_RATE).toFixed(2));
  const derivedTotal = Number((subtotal + tax).toFixed(2));
  const persistedTotal = Number(toNumber(invoice?.total).toFixed(2));

  return {
    ...invoice,
    total: estimateItems.length > 0 ? derivedTotal : persistedTotal,
    subtotal,
    tax,
    items: estimateItems.map(item => ({
      id: item.id,
      description: item.description,
      quantity: toNumber(item.quantity),
      unitPrice: toNumber(item.unitPrice),
      total: toNumber(item.total)
    }))
  };
};

const getAll = async (user) => {
  if (user.role === 'CUSTOMER') {
    const invoices = await prisma.invoice.findMany({
      where: { customerId: user.customer.id },
      include: {
        customer: true,
        payments: true,
        job: { include: { estimate: { include: { items: true } } } }
      }
    });
    return invoices.map(mapInvoiceWithPricing);
  }
  const invoices = await prisma.invoice.findMany({
    include: {
      customer: true,
      payments: true,
      job: { include: { estimate: { include: { items: true } } } }
    }
  });
  return invoices.map(mapInvoiceWithPricing);
};

const create = async (invoiceData) => {
  const { sendWithEstimate, estimateId, ...data } = invoiceData;

  let resolvedEstimateId = null;
  let linkedJobId = data.jobId ? parseInt(data.jobId, 10) : null;

  if (estimateId) {
    const estId = typeof estimateId === 'string' ? parseInt(estimateId.replace('EST-', ''), 10) : estimateId;
    if (!Number.isNaN(estId)) {
      resolvedEstimateId = estId;
      if (!linkedJobId) {
        const job = await prisma.job.findUnique({ where: { estimateId: estId } });
        if (job) linkedJobId = job.id;
      }
    }
  } else if (linkedJobId) {
    const linkedJob = await prisma.job.findUnique({ where: { id: linkedJobId } });
    resolvedEstimateId = linkedJob?.estimateId || null;
  }

  if (resolvedEstimateId) {
    const estimate = await prisma.estimate.findUnique({
      where: { id: resolvedEstimateId },
      include: { items: true, customer: true }
    });

    if (estimate) {
      const subtotal = Number(estimate.items.reduce((sum, item) => sum + toNumber(item.total), 0).toFixed(2));
      const tax = Number((subtotal * TAX_RATE).toFixed(2));
      data.total = Number((subtotal + tax).toFixed(2));
      if (!data.customerId) data.customerId = estimate.customerId;

      // Ensure invoice can always resolve real line-items via linked job->estimate,
      // even when invoice is created before estimate approval.
      if (!linkedJobId) {
        const existingJob = await prisma.job.findUnique({ where: { estimateId: estimate.id } });
        if (existingJob) {
          linkedJobId = existingJob.id;
        } else {
          const createdJob = await prisma.job.create({
            data: {
              customerId: estimate.customerId,
              estimateId: estimate.id,
              title: estimate.projectTitle || `${estimate.customer?.name || 'Customer'} Service Job`,
              description: estimate.notes || 'Autogenerated from estimate-linked invoice',
              status: 'SCHEDULED'
            }
          });
          linkedJobId = createdJob.id;
        }
      }
    }
  }

  if (data.customerId) data.customerId = parseInt(data.customerId, 10);
  if (linkedJobId) data.jobId = linkedJobId;
  data.total = toNumber(data.total);

  const invoice = await prisma.invoice.create({
    data,
    include: {
      customer: true,
      payments: true,
      job: { include: { estimate: { include: { items: true } } } }
    }
  });

  // Handle bundled send logic
  if (sendWithEstimate && estimateId) {
    const estId = typeof estimateId === 'string' ? parseInt(estimateId.replace('EST-', ''), 10) : estimateId;
    if (!Number.isNaN(estId)) {
      await prisma.estimate.update({
        where: { id: estId },
        data: { status: 'PENDING' }
      });
    }
  }

  return mapInvoiceWithPricing(invoice);
};

const update = async (id, data) => {
  const invoice = await prisma.invoice.update({
    where: { id: parseInt(id) },
    data
  });
  return await prisma.invoice.findUnique({
    where: { id: invoice.id },
    include: {
      customer: true,
      payments: true,
      job: { include: { estimate: { include: { items: true } } } }
    }
  });
};

const remove = async (id) => {
  return await prisma.invoice.delete({
    where: { id: parseInt(id) }
  });
};

module.exports = { getAll, create, update, remove };
